version: '2'
services:
  webserver:
    depends_on:
      - fe
    container_name: nginx
    build: nginx/.
    image: mpr/nginx
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    domainname: meuportaretrato.com
  fe:
    container_name: fe
    image: mpr/admin
    ports:
      - "8080:8080"
    environment:
      profile: dev
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    domainname: meuportaretrato.com.br  
